spring.application.name=workout

spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=challenge;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=dkemfrn12!

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.challenge.workout

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
