spring.application.name=workout

spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=challenge;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=dkemfrn12!

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.challenge.workout

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 솔라피 (문자 API)
coolsms.api.key=NCSMZ15ZA10HGGNF
coolsms.api.secret=56UBVI0HTVU2XEUJQZMMSIVLGF6XQWIM
coolsms.from.number=01046705838

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
